### PR TITLE
implementation

### PR DESCRIPTION
**Pull request by maddingo**
Code change from @minasgull

### CODE REVIEW

**Comment by maddingo** [comment]
@minasgull , there are a lot of tests failing, mostly due to a trailng '/' in the URL. 
The POM also has a lot of white-space changes. I would appreciate if you reverese those kind of changes. Maybe the IDE settings have to be adjusted, otherwise we get alot of whit-space changes only because people have different editor settings. In general it is good practice to go with the conventions of the projects, even if you might disagree.

**Comment by minasgull** [comment]
> @minasgull , there are a lot of tests failing, mostly due to a trailng '/' in the URL.
> The POM also has a lot of white-space changes. I would appreciate if you reverese those kind of changes. Maybe the IDE settings have to be adjusted, otherwise we get alot of whit-space changes only because people have different editor settings. In general it is good practice to go with the conventions of the projects, even if you might disagree.

ok. take a look on it tomorrow. thanks

**Comment by minasgull** [comment]
@maddingo i fixed everything. please, take a look when you have time

**Comment by maddingo** [comment]
editorconfig is meant to guarantee a consistent editor configuration across IDEs/editors. it is published by editorconfig.org and alle major editors like IntelliJ, Eclipse, vim etc have a plugin for it.

**Comment by maddingo** [comment]
The tests seem to pass. I can merge it. Could you also add a one-liner to the NEWS section in the README.
 
I lost lost a bit interest in the project. First I thought it was a goode idea, but now I think it is better to ask the server developer to publish a OAS and generate the client code from that. This creates potentially faster and more straight forward code.

**Comment by minasgull** [comment]
> editorconfig is meant to guarantee a consistent editor configuration across IDEs/editors. it is published by editorconfig.org and alle major editors like IntelliJ, Eclipse, vim etc have a plugin for it.

yeah, i know. the question was what do you think about adding it to the project? To keep editor configuration as a part of source is a good way to force contributors follow the same formatting rules

**Comment by maddingo** [comment]
Sorry about the misunderstanding about the editorconfig. Yes, I also think it is a good idea to have it in the source code. Would you mind creating a new Pull request with the editorconfig?

**Comment by maddingo** [comment]
The integration tests fail, but this is probably due to wrong test implementation and because of your changes.

**Pull request merged**
